"""use user role enum

Revision ID: a52c23df9918
Revises: 07485a9fa826
Create Date: 2026-09-05 22:50:56.732242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a52c23df9918'
down_revision: Union[str, Sequence[str], None] = '07485a9fa826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    userrole = postgresql.ENUM(
        'user',
        'admin',
        name='userrole'
    )

    userrole.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(length=50),
        type_=userrole,
        existing_nullable=False,
        postgresql_using='role::userrole'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    userrole = postgresql.ENUM(
        'user',
        'admin',
        name='userrole'
    )

    op.alter_column(
        'users',
        'role',
        existing_type=userrole,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False
    )

    userrole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
